version: '3'
services:
  db:
    image: 'postgres:15.1'
    container_name: ngcash_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "ngcash_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 5s
    volumes:
      - ./ngcash_data:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    image: 'ngcash:v1'
    container_name: ngcash
    command: sh -c "npm run typeorm migration:run && npm run dev"
    ports:
      - '4000:4000'
    volumes:
      - '.:/var/www/app'
    depends_on:
      db:
        condition: service_healthy
volumes:
  ngcash_data: {}
