version: '3'
services:
  app:
    build: .
    restart: always
    image: 'ngcashweb:v1'
    container_name: ngcashweb
    ports:
      - '3000:3000'
    volumes:
      - '.:/var/www/web'
volumes:
  ngcash_data: {}
